use crate::core::scanners::{Scanner, ScannerType};
use crate::shared::config::JackSparrowConfig;
use crate::shared::context::ScanContext;
use crate::shared::error::JackSparrowError;
use crate::shared::types::{Confidence, Evidence, Finding, Severity, VulnerabilityType};
use async_trait::async_trait;
use reqwest::Client;

/// WAF signature fingerprinting entry
struct WafSignature {
	/// WAF/CDN name
	name: &'static str,
	/// Headers that indicate this WAF (header name, optional value substring)
	headers: Vec<(&'static str, Option<&'static str>)>,
	/// Cookies that indicate this WAF
	cookies: Vec<&'static str>,
	/// Status codes that indicate this WAF blocking
	blocking_status: Vec<u16>,
	/// Response body patterns
	body_patterns: Vec<&'static str>,
	/// Detection confidence boost
	confidence_boost: f64,
}

/// Build the WAF fingerprint database
fn waf_signatures() -> Vec<WafSignature> {
	vec![
		WafSignature {
			name: "Cloudflare",
			headers: vec![
				("cf-ray", None),
				("cf-cache-status", None),
				("server", Some("cloudflare")),
			],
			cookies: vec!["__cflb", "__cfuid", "cf_clearance"],
			blocking_status: vec![403, 503],
			body_patterns: vec![
				"Cloudflare",
				"cf-browser-verification",
				"ray ID",
				"Attention Required! | Cloudflare",
			],
			confidence_boost: 0.2,
		},
		WafSignature {
			name: "AWS CloudFront / AWS WAF",
			headers: vec![
				("x-amz-cf-id", None),
				("x-amz-cf-pop", None),
				("server", Some("cloudfront")),
				("x-amzn-requestid", None),
			],
			cookies: vec![],
			blocking_status: vec![403],
			body_patterns: vec!["x-amzn", "RequestId"],
			confidence_boost: 0.15,
		},
		WafSignature {
			name: "Akamai",
			headers: vec![
				("x-akamai-transformed", None),
				("server", Some("AkamaiGHost")),
				("x-cache", Some("akamai")),
			],
			cookies: vec!["akamai_"],
			blocking_status: vec![403, 406],
			body_patterns: vec!["Reference&#32;", "Akamai"],
			confidence_boost: 0.2,
		},
		WafSignature {
			name: "AWS WAF (native)",
			headers: vec![],
			cookies: vec!["aws-waf-token"],
			blocking_status: vec![403],
			body_patterns: vec!["AWS WAF", "awswaf"],
			confidence_boost: 0.25,
		},
		WafSignature {
			name: "Sucuri WAF",
			headers: vec![
				("x-sucuri-id", None),
				("server", Some("Sucuri")),
			],
			cookies: vec!["sucuri_cloudproxy_"],
			blocking_status: vec![403],
			body_patterns: vec!["Sucuri", "Access Denied"],
			confidence_boost: 0.25,
		},
		WafSignature {
			name: "ModSecurity / Mod_Evasive",
			headers: vec![],
			cookies: vec![],
			blocking_status: vec![403, 406],
			body_patterns: vec![
				"mod_security",
				"ModSecurity",
				"This error was generated by Mod_Security",
			],
			confidence_boost: 0.2,
		},
		WafSignature {
			name: "Incapsula / Imperva",
			headers: vec![
				("x-iinfo", None),
				("server", Some("cloudflare")),
			],
			cookies: vec!["incap_ses", "visid_incap_"],
			blocking_status: vec![403],
			body_patterns: vec!["Incapsula", "imperva"],
			confidence_boost: 0.2,
		},
		WafSignature {
			name: "F5 BIG-IP ASM",
			headers: vec![
				("server", Some("BIG-IP")),
				("x-cnection", None),
			],
			cookies: vec!["TS*", "BIGipServer"],
			blocking_status: vec![403],
			body_patterns: vec!["The requested URL was rejected", "BIG-IP"],
			confidence_boost: 0.25,
		},
		WafSignature {
			name: "Barracuda WAF",
			headers: vec![],
			cookies: vec!["barra_counter_session"],
			blocking_status: vec![403],
			body_patterns: vec!["Barracuda", "barracuda"],
			confidence_boost: 0.2,
		},
		WafSignature {
			name: "DenyAll / Imperva",
			headers: vec![
				("server", Some("DYNSRC")),
				("x-true-cache-key", None),
			],
			cookies: vec![],
			blocking_status: vec![403, 424, 509],
			body_patterns: vec![],
			confidence_boost: 0.15,
		},
		WafSignature {
			name: "FortiWeb",
			headers: vec![],
			cookies: vec![],
			blocking_status: vec![403],
			body_patterns: vec!["FortiGuard", "Server Unavailable!"],
			confidence_boost: 0.2,
		},
		WafSignature {
			name: "Wordfence",
			headers: vec![],
			cookies: vec!["wfwaf-authcookie"],
			blocking_status: vec![403],
			body_patterns: vec!["Wordfence", "Generated by Wordfence"],
			confidence_boost: 0.3,
		},
	]
}

/// WAF Detection scanner
///
/// Detects Web Application Firewalls and CDN protections by analyzing:
/// 1. Response headers for WAF-specific signatures
/// 2. Cookies for WAF session tokens
/// 3. Response body for WAF block pages
/// 4. Status codes indicative of WAF blocking
pub struct WafDetectionScanner;

impl WafDetectionScanner {
	pub fn new(_config: &JackSparrowConfig) -> Self {
		Self
	}

	/// Check if a status code is a WAF blocking indicator
	fn is_blocking_status(status: u16, signatures: &[WafSignature]) -> Option<&'static str> {
		for sig in signatures {
			if sig.blocking_status.contains(&status) {
				return Some(sig.name);
			}
		}
		None
	}
}

#[async_trait]
impl Scanner for WafDetectionScanner {
	fn scanner_type(&self) -> ScannerType {
		ScannerType::WafDetection
	}

	async fn scan(
		&self,
		target: &str,
		_config: &JackSparrowConfig,
		context: &ScanContext,
	) -> Result<Vec<Finding>, JackSparrowError> {
		// Build client with auth headers
		let mut headers = reqwest::header::HeaderMap::new();
		for (key, value) in &context.headers {
			if let (Ok(name), Ok(val)) = (
				reqwest::header::HeaderName::from_bytes(key.as_bytes()),
				reqwest::header::HeaderValue::from_str(value),
			) {
				headers.insert(name, val);
			}
		}
		if let Some(ref cookies) = context.cookies {
			if let Ok(val) = reqwest::header::HeaderValue::from_str(cookies) {
				headers.insert(reqwest::header::COOKIE, val);
			}
		}

		let client = Client::builder()
			.default_headers(headers)
			.timeout(std::time::Duration::from_secs(15))
			.build()
			.map_err(|e| JackSparrowError::ToolExecutionFailed {
				tool: "waf-scanner".to_string(),
				message: e.to_string(),
			})?;

		// Phase 1: Normal request to fingerprint WAF
		let response = client.get(target).send().await.map_err(|e| {
			JackSparrowError::ToolExecutionFailed {
				tool: "waf-scanner".to_string(),
				message: e.to_string(),
			}
		})?;

		let status = response.status().as_u16();
		let response_headers = response.headers().clone();
		let body = response.text().await.unwrap_or_default();

		// Extract cookie names from Set-Cookie headers
		let mut cookie_names: Vec<String> = Vec::new();
		for (name, _) in &response_headers {
			if name == "set-cookie" {
				// Parse cookie name from "name=value; ..." format
				if let Some(cookie_str) = response_headers.get(name).and_then(|v| v.to_str().ok()) {
					if let Some(cookie_name) = cookie_str.split('=').next() {
						cookie_names.push(cookie_name.trim().to_lowercase());
					}
				}
			}
		}
		let signatures = waf_signatures();

		let mut detected_wafs: Vec<(String, f64, String)> = Vec::new(); // (name, confidence, evidence)

		// Phase 2: Check headers against signatures
		for sig in &signatures {
			let mut header_matches = 0;
			let mut evidence_parts = Vec::new();

			for (header_name, header_value_opt) in &sig.headers {
				if let Some(header_val) = response_headers.get(*header_name).and_then(|v| v.to_str().ok()) {
					let matched = match header_value_opt {
						Some(expected) => header_val.to_lowercase().contains(&expected.to_lowercase()),
						None => true,
					};
					if matched {
						header_matches += 1;
						evidence_parts.push(format!("{}: {}", header_name, header_val));
					}
				}
			}

			if header_matches > 0 {
				let confidence = 0.5 + sig.confidence_boost * (header_matches as f64);
				detected_wafs.push((
					sig.name.to_string(),
					confidence.min(0.95),
					evidence_parts.join(", "),
				));
			}
		}

		// Phase 3: Check cookies
		for sig in &signatures {
			for cookie_pattern in &sig.cookies {
				let found = cookie_names.iter().any(|c| {
					c.contains(&cookie_pattern.to_lowercase())
				});
				if found {
					// Check if already detected
					if !detected_wafs.iter().any(|(name, _, _)| name == sig.name) {
						detected_wafs.push((
							sig.name.to_string(),
							0.7 + sig.confidence_boost,
							format!("Cookie pattern: {}", cookie_pattern),
						));
					}
				}
			}
		}

		// Phase 4: Check body patterns
		for sig in &signatures {
			for pattern in &sig.body_patterns {
				if body.to_lowercase().contains(&pattern.to_lowercase()) {
					if !detected_wafs.iter().any(|(name, _, _)| name == sig.name) {
						detected_wafs.push((
							sig.name.to_string(),
							0.6 + sig.confidence_boost,
							format!("Body pattern: {}", pattern),
						));
					}
				}
			}
		}

		// Phase 5: Check if we got blocked (high status code = likely WAF)
		if status >= 400 {
			if let Some(waf_name) = Self::is_blocking_status(status, &signatures) {
				if !detected_wafs.iter().any(|(name, _, _)| name == waf_name) {
					detected_wafs.push((
						waf_name.to_string(),
						0.5,
						format!("Blocking status code: {}", status),
					));
				}
			}
		}

		// Generate findings
		let mut findings = Vec::new();

		if detected_wafs.is_empty() {
			// No WAF detected — informational
			let mut finding = Finding::new(
				VulnerabilityType::WafDetected,
				Severity::Info,
				Confidence::Confirmed,
				"No WAF/CDN detected".to_string(),
				target.to_string(),
				"waf-scanner".to_string(),
			);
			finding.description = "No Web Application Firewall or CDN protection was detected. \
				The target may be directly exposed to attacks."
				.to_string();
			finding.evidence = Evidence {
				request: Some(format!("GET {} HTTP/1.1", target)),
				response: Some(format!("Status: {}, No WAF signatures matched", status)),
				payload: None,
				pattern: None,
				context: None,
			};
			finding.remediation = "Consider deploying a WAF (Cloudflare, AWS WAF, ModSecurity, etc.) \
				to protect against common web attacks."
				.to_string();
			finding.references = vec![
				"https://owasp.org/www-community/Controls/Web_Application_Firewall".to_string(),
			];
			finding.cvss_score = Some(0.0);
			finding.cwe_id = Some("CWE-16".to_string());
			findings.push(finding);
		} else {
			// WAF(s) detected — informational (not a vulnerability, but useful intel)
			for (waf_name, confidence, evidence) in &detected_wafs {
				let confidence_level = if *confidence >= 0.8 {
					Confidence::Confirmed
				} else if *confidence >= 0.5 {
					Confidence::Likely
				} else {
					Confidence::Possible
				};

				let mut finding = Finding::new(
					VulnerabilityType::WafDetected,
					Severity::Info,
					confidence_level,
					format!("WAF/CDN detected: {}", waf_name),
					target.to_string(),
					"waf-scanner".to_string(),
				);
				finding.description = format!(
					"A Web Application Firewall or CDN '{}' was detected protecting the target. \
					 This affects how vulnerability scanning should be performed (WAF bypass techniques may be needed).",
					waf_name
				);
				finding.evidence = Evidence {
					request: Some(format!("GET {} HTTP/1.1", target)),
					response: Some(format!("Status: {}", status)),
					payload: None,
					pattern: Some(waf_name.clone()),
					context: Some(evidence.clone()),
				};
				finding.remediation = "This is informational. WAF detection helps tune subsequent \
					vulnerability scanning to use appropriate bypass techniques."
					.to_string();
				finding.references = vec![
					"https://owasp.org/www-community/Controls/Web_Application_Firewall".to_string(),
				];
				finding.cvss_score = Some(0.0);
				finding.cwe_id = Some("CWE-16".to_string());
				findings.push(finding);
			}
		}

		Ok(findings)
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_waf_signatures_not_empty() {
		let sigs = waf_signatures();
		assert!(sigs.len() >= 10);
	}

	#[test]
	fn test_cloudflare_signature_has_required_fields() {
		let sigs = waf_signatures();
		let cf = sigs.iter().find(|s| s.name == "Cloudflare").unwrap();
		assert!(!cf.headers.is_empty());
		assert!(!cf.body_patterns.is_empty());
		assert!(cf.confidence_boost > 0.0);
	}

	#[test]
	fn test_is_blocking_status() {
		let sigs = waf_signatures();
		// 403 could match several WAFs
		let result = WafDetectionScanner::is_blocking_status(403, &sigs);
		assert!(result.is_some());
	}

	#[test]
	fn test_is_blocking_status_normal() {
		let sigs = waf_signatures();
		let result = WafDetectionScanner::is_blocking_status(200, &sigs);
		assert!(result.is_none());
	}

	#[test]
	fn test_all_waf_signatures_have_name() {
		let sigs = waf_signatures();
		for sig in &sigs {
			assert!(!sig.name.is_empty());
		}
	}
}
